### ISSUE TITLE
想用但是有点抓瞎......-_-||

### ISSUE THREAD

**Issue by kklod** [BaoXuebin/beancount-node-server#1]
非程序员，目前在用beancount记账，也是苦恼于移动端记账问题。
我看你这个demo挺有意思的，大概是我想要的样子。

问：

- 这个是需要重新配置账本文件呢还是用既有的就可以？
- 我是利用include功能分了多个账本文件的，交易录入后最终数据是保存在哪个账本？ 
- 如果要用你的远程访问编辑的个功能，我是否是需要把账本文件上传至网络？

外行问的问题，有点傻  见谅哈...

望解答，谢谢！

**Comment by BaoXuebin** [comment]
Q1. 这个是需要重新配置账本文件呢还是用既有的就可以？
A: 不用，在 `config/config.json` 中的 `/dataPath` 改成你现有 beancount 所在目录就行。

Q2. 我是利用include功能分了多个账本文件的，交易录入后最终数据是保存在哪个账本？
A: 如果你之前是使用 fava 记账，默认的数据是保存到 `index.bean`。我这个项目是按月进行账本拆分，交易数据会按照日期，保存到对应月的账本中，例如：2021-08-11 的账目会记录到 `month/2021-08.bean` 文件。

Q3. 如果要用你的远程访问编辑的这个功能，我是否是需要把账本文件上传至网络？
A: 这个问题也是我在考虑的问题，账本是很隐私的数据，我不建议把记账信息上传到任何第三方平台；我这个项目的一个方向也是提供私有化部署。

目前还在开发阶段，有不懂或者使用中的问题欢迎留言交流，感谢！
